[workspace]
members = [
    "circuits/transfer",
    "circuits/lock",
    "circuits/withdraw",
    "circuits/process_pending_deposits",
    "circuits/process_pending_transfers",
    "circuits/add_eth_signers",
]
default-member = "circuits/transfer"

